### ISSUE TITLE
Missing Algorithms

### ISSUE THREAD

**Issue by williamfiset** [williamfiset/Algorithms#1]
Still need to code up and document usage of how to use the following algorithms. Help is of course always appreciated :)

# Graph Theory

### Tree related
- [ ] Centroid decomposition
- [ ] Heavy-Light decomposition
  - [ ] Distance between two nodes
  - [ ] Lowest common ancestor
- [x] Tree Center(s)
- [x] Tree Diameter
- [x] Tree Isomorphism/canonical form, O(V+E)
- [x] Rooting tree

# Strings
- [ ] Aho-Corasick 
- [ ] Boyer-Moore
- [ ] Burrows Wheeler
- [x] Longest repeated substring(s)
- [x] Longest common substring(s)
- [x] Suffix array LCP Kasai algorithm
- [x] Suffix array string match O(mlogn)
- [ ] Suffix array string match O(m + logn)
- [ ] Z-Algorithm

**Comment by micahstairs** [comment]
This is a pretty impressive list of algorithms!

**Comment by williamfiset** [comment]
@FinnLidbetter can you upload the working modular gaussian elimination once it's done? Thanks.

**Comment by FinnLidbetter** [comment]
Yep, I'll put it up once it's fixed.

**Comment by williamfiset** [comment]
Closing issue because I made individual issues for each of these.
