### ISSUE TITLE
I do not seem to be able to compile and run the source 

### ISSUE THREAD

**Issue by bitflame** [williamfiset/Algorithms#107]
Hi 
I tried to compile the FordFulkersonExample source, but I get the following error. 
C:\Users\usr\source\JavaSource\Algorithms>javac com\williamfiset\algorithms\graphtheory\networkflow\examples\FordFulkersonExample.java
com\williamfiset\algorithms\graphtheory\networkflow\examples\FordFulkersonExample.java:102: error: cannot create array with '<>'
      graph = new List<> [n];
                      ^
1 error
I did try to change the generic type to Edge, but I get another method stating "Edge type could not be found."

**Comment by bitflame** [comment]
Windows directory path vs. *.nix.

**Comment by williamfiset** [comment]
Interesting. What JDK version do you have? Seems to be a Java version issue. What does the command "javac -version" produce? I suspect you need at least java 8?

**Comment by bitflame** [comment]
Yes, it was strange. I found that 1- I had to compile from the /Algorigthms directory like you said, and 2- I had to use "/" to get to the target file like so: 
C:\Users\usr\source\JavaSource\Algorithms>javac com\williamfiset\algorithms\graphtheory\TarjanAdjacencyMatrix.java

C:\Users\usr\source\JavaSource\Algorithms>java com\williamfiset\algorithms\graphtheory\TarjanAdjacencyMatrix
Error: Could not find or load main class com\williamfiset\algorithms\graphtheory\TarjanAdjacencyMatrix

C:\Users\usr\source\JavaSource\Algorithms>java com/williamfiset/algorithms/graphtheory/TarjanAdjacencyMatrix
Strong connected component count: 4
Strong connected components:
[2, 2, 2, 1, 1, 1, 1, 0, 0, 3]

I seem to be able to compile the source with backslash, but in order to run it from the /Algorigthms directory I have to use "/". 
By the way, thank you so much for the video, it is helping me a lot.
