### ISSUE TITLE
Bellman Ford : Do you really need to run the loop V-1 times to check for negative cycles

### ISSUE THREAD

**Issue by shanurrahman** [williamfiset/Algorithms#108]
Bellman Ford, Adjacency list solution

Even if you relax the edges once more after the optimal solution has been reached, and you end up getting a better solution will mean that our graph has negative cycle....

I am attaching a solution I wrote in python
`
from collections import defaultdict
class Graph:
    def __init__(self, V):
        self.g = defaultdict(list)
        self.V = V

    def addEdge(self, s, e, w):
        self.g[s].append((s, e, w))

    def printg(self):
        print(self.g)

    def glength(self):
        return len(self.g)

    def bellmanFord(self, s):
        self.dist = [float("inf")]*self.V
        self.dist[0] = 0
        for i in range(self.V-1):
            # calling the values will give us all the edges in a list
            # [(), ()] and then we can iterate over them one by one by one
            for edges in self.g.values():
                for edge in edges:
                    snode, enode, wt = edge
                    if(self.dist[snode]+wt < self.dist[enode]):
                        self.dist[enode]= self.dist[snode]+wt

        # check for negative cycles, just run relax step once
        for edges in self.g.values():
            for edge in edges:
                snode, enode, wt = edge
                if(self.dist[snode]+wt < self.dist[enode]):
                    self.dist[enode] = float("-inf")
        return self.dist

g = Graph(9)
g.addEdge(0, 1, 1)
g.addEdge(1, 2, 1)
g.addEdge(2, 4, 1)
g.addEdge(4, 3, -3)
g.addEdge(3, 2, 1)
g.addEdge(1, 5, 4)
g.addEdge(1, 6, 4)
g.addEdge(5, 6, 5)
g.addEdge(6, 7, 4)
g.addEdge(5, 7, 3)

dist = g.bellmanFord(0)
print dist
`

In place of to and from I used snode, enode. The example is the same as yours

**Comment by williamfiset** [comment]
In my code, I am propagating the negative cycles, not trying to detect the existence of. I'm pretty sure propagating the negative cycles throughout the graph would take V-1 iterations. Propagating the negative cycles gives you more information than just detecting the existence of cycles. For example, propagation lets you can solve problems like [this](https://open.kattis.com/problems/shortestpath3).
