### ISSUE TITLE
How does the for loop iterate ? 

### ISSUE THREAD

**Issue by ROHROCK** [williamfiset/Algorithms#116]
How does the for loop iterate? Since the variable 

> **at** 

does not get updated here in the loop
https://github.com/williamfiset/Algorithms/blob/a98aa532900a3e8fa2e41be73600f30e5b5ad3a2/com/williamfiset/algorithms/graphtheory/DijkstrasShortestPathAdjacencyList.java#L108

**Comment by williamfiset** [comment]
Yes it does. Last statement "at = prev[at]"
