### ISSUE TITLE
Add remove() api in RedBlackTree implementation

### ISSUE THREAD

**Issue by bhaskar253** [williamfiset/Algorithms#118]
RedBlackTree implementation is missing the 

> remove(T elem)

**Comment by williamfiset** [comment]
Agreed, this would be nice. Feel free to send a PR

**Comment by bhaskar253** [comment]
Hey @williamfiset, I tried implementing but I am not able to handle root node deletion.

**Comment by abstratt** [comment]
Same as #80?

**Comment by williamfiset** [comment]
Duplicate of #80, thanks Rafael
