### ISSUE TITLE
Extra comma at the end of toString() method in DoubleLinkedList data structure code

### ISSUE THREAD

**Issue by SamuelAl** [williamfiset/Algorithms#133]
Hello,
I noticed that in the toString() function of the DoubleLinkedList data structure an extra comma is added to the string after the last element. I would like to submit code to eliminate that comma if that is a feature that you would like to be optimized.

**Comment by williamfiset** [comment]
There's this PR, but it conflicts with the master branch:

https://github.com/williamfiset/Algorithms/pull/109
