### ISSUE TITLE
Empty Eulerian Path Bug

### ISSUE THREAD

**Issue by williamfiset** [williamfiset/Algorithms#146]
From a comment I got on YouTube that needs investigation:

"If the graph has 3 nodes - 0, 1, 2 and the indegree and outdegree of all the nodes are 0. Then, there is an empty Eulerian path, but the code results in "0". Do you think findStartNode() can be enhanced to handle this edge case?"

Relevant Videos:

Euler path/circuit existence: https://youtu.be/xR4sGgwtR2I
Euler path/circuit algorithm: https://youtu.be/8MpoO2zA2l4
Euler path/circuit source code: https://www.youtube.com/watch?v=QQ3jO1dKjYQ

Code:

https://github.com/williamfiset/Algorithms/blob/master/src/main/java/com/williamfiset/algorithms/graphtheory/EulerianPathDirectedEdgesAdjacencyList.java

Tests:

https://github.com/williamfiset/Algorithms/blob/master/src/test/java/com/williamfiset/algorithms/graphtheory/EulerianPathDirectedEdgesAdjacencyListTest.java

We should add tests for this edge case and/or fix the code.

**Comment by leeib3041** [comment]
I don't know if I'm misinterpreting the quote, but the scenario I created:
```
private static void emptyEulerianPathBug() {
    int n = 3;
    List<List<Integer>> graph = initializeEmptyGraph(n);

    addDirectedEdge(graph, 0, 0);
    addDirectedEdge(graph, 1, 0);
    addDirectedEdge(graph, 2, 0);

    EulerianPathDirectedEdgesAdjacencyList solver;
    solver = new EulerianPathDirectedEdgesAdjacencyList(graph);

    System.out.println(Arrays.toString(solver.getEulerianPath()));
  }
```
prints "null" and not 0. I have tried few other ways that I interpreted as:
(0,0) (0,1) (0,2) (1,0) (2,0) = [2, 0, 1, 0, 0, 2]
and
(0,1) (0,2) (1,0) (2,0) = [2, 0, 1, 0, 2]
and
(1,0) (2,0) = null 
and
(0,0) (1,1) (2,2) = null

**Comment by williamfiset** [comment]
You need to make sure "indegree and outdegree of all the nodes are 0" aka there are no edges, and this is when the bug should appear

**Comment by leeib3041** [comment]
Maybe I'm a little late to the game, but if that's the case it seems like someone has already fixed it.
The code in your youtube video
```
private boolean graphHasEulerianPath() {
    int startNodes = 0, endNodes = 0;
    for (int i = 0; i < n; i++) {
      if (out[i] - in[i] > 1 || in[i] - out[i] > 1) return false;
      else if (out[i] - in[i] == 1) startNodes++;
      else if (in[i] - out[i] == 1) endNodes++;
    }
```
the code in your repo
```
private boolean graphHasEulerianPath() {
    **if (edgeCount == 0) return false;** <------ the change
    int startNodes = 0, endNodes = 0;
    for (int i = 0; i < n; i++) {
      if (out[i] - in[i] > 1 || in[i] - out[i] > 1) return false;
      else if (out[i] - in[i] == 1) startNodes++;
      else if (in[i] - out[i] == 1) endNodes++;
    }
```
Which is strange because your reply on the youtube video was 4weeks ago (as well as this issue), but the corrected source code was last edited 3 months ago.

**Comment by williamfiset** [comment]
I filed the bug without actually verifying the legitimacy of the claim, therefore it's very well possible that I fixed the issue prior to the YouTube comment, in which case this issue is already resolved haha. I will take a closer look tonight to make sure everything is in order

**Comment by williamfiset** [comment]
@leeib3041 I'm confirming that it looks like the case where all indegrees and outdegrees are zero returns a null path, as we expect.
