### ISSUE TITLE
Add Self Organizing List implementation

### ISSUE THREAD

**Issue by EAlexa** [williamfiset/Algorithms#159]
See [Self-organizing_list](https://en.wikipedia.org/wiki/Self-organizing_list) for details. 
Frequently searched elements will move towards the head of the list.

**Comment by williamfiset** [comment]
It's this already implemented as a SplayTree?

https://github.com/williamfiset/Algorithms/blob/master/src/main/java/com/williamfiset/algorithms/datastructures/binarysearchtree/SplayTree.java

**Comment by EAlexa** [comment]
A SplayTree is a binary tree, a list is just a list, though it is, partly, the same

**Comment by bbowles98** [comment]
Could I take a shot at this?

**Comment by williamfiset** [comment]
No, there's PR https://github.com/williamfiset/Algorithms/pull/161

**Comment by williamfiset** [comment]
Closing this issue, I don't think there's a whole lot of value in having this.
