### ISSUE TITLE
Improve PriorityQueue construction to O(n) with heapify 

### ISSUE THREAD

**Issue by williamfiset** [williamfiset/Algorithms#169]
When a binary heap is created from a primitive array of values, we heapify the array to create a binary heap in O(n). However, when a collection is passed into the constructor, we lazily add elements to the PQ resulting in O(nlog(n)) construction. Let's investigate if we can also heapify the collection constructor.

O(n) construction with heapify:
https://github.com/williamfiset/Algorithms/blob/master/src/main/java/com/williamfiset/algorithms/datastructures/priorityqueue/BinaryHeap.java#L29

O(nlog(n)) construction without heapify:
https://github.com/williamfiset/Algorithms/blob/master/src/main/java/com/williamfiset/algorithms/datastructures/priorityqueue/BinaryHeap.java#L42

**Comment by Ninad99** [comment]
I can work on this
