### ISSUE TITLE
Boore moore algorithm is not working

### ISSUE THREAD

**Issue by NuwanHarsha** [williamfiset/Algorithms#174]
https://github.com/williamfiset/Algorithms/blob/master/src/main/java/com/williamfiset/algorithms/strings/BoyerMooreStringSearch.java

text = AABAACAADAABAABA
pattern = AABA
not working for this pattern and text.

**Comment by williamfiset** [comment]
Thanks for reporting this, sometimes these things slip through. I see that the snippet is currently marked as untested, what a surprise. @NuwanHarsha do you want to try and fix it?

**Comment by williamfiset** [comment]
Removed from README temporarily in b6b5b04f654350214c3af7f4c95b90df9bca16b8

**Comment by sharoha** [comment]
I see that this issue is still open. If no one has been assigned yet, can I take this issue?

**Comment by sharoha** [comment]
Raised a PR for the fix. Could you please review it?

**Comment by williamfiset** [comment]
Yes will do
