### ISSUE TITLE
Bugs of IntQueue

### ISSUE THREAD

**Issue by ttskym** [williamfiset/Algorithms#189]
```
 public IntQueue(int maxSize) {
    front = end = 0;
    sz = maxSize + 1;
    ar = new int[sz];
  }

  // Return true/false on whether the queue is empty
  public boolean isEmpty() {
    return front == end;
  }

  // Return the number of elements inside the queue
  public int size() {
    if (front > end) return (end + sz - front);
    return end - front;
  }


  // Add an element to the queue
  public void enqueue(int value) {
    ar[end] = value;
    if (++end == sz) end = 0;
    if (end == front) throw new RuntimeException("Queue too small!");
  }

  // Make sure you check is the queue is not empty before calling dequeue!
  public int dequeue() {
    int ret_val = ar[front];
    if (++front == sz) front = 0;
    return ret_val;
  }

```
Assume the maxSize is 5. 
ar: [0, 0 , 0, 0, 0, 0]
and push 1, 2, 3, 4, 5  one by one. now the ar, sz, front and end are :
ar: [1, 2,3,4,5,0]
end:5
front: 0
sz: 6
and then , we push the 6, so the method enqueue starts to execute:
ar[5] = 6;
end == sz == 6, so end = 0;
end == front, the exception shows.

however, the queue is just full now and should not throw an exception.

besides the above, the queue should be circular.

**Comment by williamfiset** [comment]
You said the max size was 5, but you're adding a 6th element. I don't think this is a bug?

**Comment by ttskym** [comment]
> You said the max size was 5, but you're adding a 6th element. I don't think this is a bug?

Emmm, it is really not a functional bug. but It looks a little weird. I do not understand why we need extra variable Sz(maxSize + 1) and there is always a blank place in the array ar that will never use.

**Comment by williamfiset** [comment]
I think I added a space to prevent index out of bounds errors. Feel free to adjust the data structure for any bugs/improvements.
