### ISSUE TITLE
Eulerian Path/Circuit algorithm (Video) question.

### ISSUE THREAD

**Issue by RebelCoderRU** [williamfiset/Algorithms#191]
Hello.
I have watched and understood all the steps. Code seems to work on small datasets from the course I am doing, but fails on large data sets.

Here is one example:
[http://bioinformaticsalgorithms.com/data/extradatasets/assembly/eulerian_cycle.txt](url)

This fails on path/cycle validation stage. Can anyone try running this and see why this is happening?

It fails at this check:

```
  for pos in range(len(in_degrees)):
        print(out_degrees[pos], in_degrees[pos])
        # Make sure a Node has no Extra in/out edges
        if out_degrees[pos] - in_degrees[pos] > 1 or \
                in_degrees[pos] - out_degrees[pos] > 1:
            return False
```

**Comment by RebelCoderRU** [comment]
UPDATE: The problem was on my side in these two functions:

```
count_out_degrees(adjacency_dict):
count_in_degrees(adjacency_dict):
```

If someone is coding this in Python and uses dictionaries, you might run into a problem of how it is sorted and read. Make sure your logic for those two/one function accounts for proper sorting.

**Comment by RebelCoderRU** [comment]
Actually, it seems that our code does not handle things like this:

```
0 -> 2
1 -> 3
2 -> 1
3 -> 0,4
6 -> 3,7
7 -> 8
8 -> 9
9 -> 6
```

```
6->7->8->9->6->3->0->2->1->3->4
```

As node 4 in not in the list and this is normal. It will be the last one in the output.

**Comment by williamfiset** [comment]
@RebelCoderRU the output produced by the algorithm looks good to me. The graph you provided has an Eulerian path, but no Eulerian cycle. The unique starting node is 6, and the unique ending node is 4. There are 10 edges in the graph, and all 10 edges were visited. What's the issue?

**Comment by RebelCoderRU** [comment]
Data provided above is a Test Sample. It has both, Input and the expected output. If we input the data into the algorithm we wrote in your video, it fails as there are no nodes 4, 5 in the HashMap/Dictionary keys? Right?

**Comment by williamfiset** [comment]
Added a test, everything checks out.
