### ISSUE TITLE
Null pointer 

### ISSUE THREAD

**Issue by omedia23** [williamfiset/Algorithms#193]
https://github.com/williamfiset/Algorithms/blob/d3b79cf50e096b1d65bdf7e8bf12c9416496c5f8/src/main/java/com/williamfiset/algorithms/datastructures/linkedlist/DoublyLinkedList.java#L63

when the first element are added to the linked list then the head and tail are assigned to null. But the problem is when we add the second element we added that by adding a new reference to the tail but which is null.

**Comment by williamfiset** [comment]
Are you sure? I think we have tests for exactly that. Can you provide an example?

https://github.com/williamfiset/Algorithms/blob/d3b79cf50e096b1d65bdf7e8bf12c9416496c5f8/src/test/java/com/williamfiset/algorithms/datastructures/linkedlist/LinkedListTest.java#L61

**Comment by williamfiset** [comment]
Closing since there was no response
