### ISSUE TITLE
readme emojis

### ISSUE THREAD

**Issue by nrowley** [williamfiset/Algorithms#201]
this is a fairly insignificant issue but on my mac, the 🎥  (the link to videos of the algorithm) emoji overlaps the text.
I am not sure whether this is intended but I would happily fix the issue for you.

![Screenshot 2020-07-17 at 15 19 14](https://user-images.githubusercontent.com/47508642/87796156-e4c80f80-c840-11ea-8e54-e042c4e425d2.png)

**Comment by williamfiset** [comment]
What browser are you using? They don't overlap for me, but the emoji is very close to the text. Feel free to investigate and submit a fix

**Comment by nrowley** [comment]
I am using google chrome on mac os catalina version 85.0.4183.26.

**Comment by nrowley** [comment]
I have created a PR could you please review it? #202

**Comment by nrowley** [comment]
hopefully this should fix it for everyone.

**Comment by nrowley** [comment]
I have created a PR for this issue, I think this fixes it.

#203
