### ISSUE TITLE
Potential improvement on TarjanSccSolverAdjacencyList.java

### ISSUE THREAD

**Issue by ghShu** [williamfiset/Algorithms#218]
Two potential improvements

1. Line 68: `if` condition check is not necessary since dfs(to) will push `to` node into stack. Therefore, the operation after if clause can be safely executed after dfs(to)
2. The condition that could really be checked is that `to` node was already in the stack when entering this level of DFS. The pseudo will look like this:
for (to : graph.get(at)) {
  if ids[to] == UNVISITED: {
   dfs(to);
  low[at] = Math.min(low[at], low[to]);
 } else if (onStack[to]) {
  low[at] = Math.min(low[at], ids[to]);
}
} 

Please see details in the original paper: https://pdfs.semanticscholar.org/3857/42fffcf113656f0d3cf6c06ef95cb8439dc6.pdf
Please let me know how do you think? @williamfiset

**Comment by williamfiset** [comment]
lgtm

**Comment by ghShu** [comment]
Hello William, I made a PR for this. Please take a look.

**Comment by williamfiset** [comment]
Thanks!
