### ISSUE TITLE
Wrong Example output  in EulerianPathDirectedEdgesAdjacencyList

### ISSUE THREAD

**Issue by BrahianVT** [williamfiset/Algorithms#219]
Well there is a simple mistakes not so important  but mistake in the end.

In this example EulerianPathDirectedEdgesAdjacencyList with the test at smallExample() 
[Here](https://github.com/williamfiset/Algorithms/blob/3256a65aeefa0c7a48067b04e4b474c2902d804a/src/main/java/com/williamfiset/algorithms/graphtheory/EulerianPathDirectedEdgesAdjacencyList.java)

the result is also correct but the  result of the eulerian Path  for the graph is  "0, 1, 4, 1, 2, 1, 3]" instead of   "[0, 1, 2, 1, 4, 1, 3]" for the given graph.

**Comment by williamfiset** [comment]
Thanks fixed
