### ISSUE TITLE
Possible bug in Tarjan's algorithm

### ISSUE THREAD

**Issue by williamfiset** [williamfiset/Algorithms#221]
I need to investigate Tarjan's algorithm to figure out if there's a bug. Multiple comments on the Tarjan's [video](https://www.youtube.com/watch?v=wUgWX0nc4NY) indicate a possible issue. Furthermore, I have tried solving 2 competitive programming problems [\[1\]](https://open.kattis.com/problems/equivalences)[\[2\]](https://open.kattis.com/problems/runningmom) using the algorithm in this repo and have run into both runtime and wrong answers. Whatever is going on may warrant a video remake.

**Comment by developer0395** [comment]
I was also confuse with `low[at] = min(low[at], ids[to]);` On Wikipedia found this: 

> Note that `v.lowlink := min(v.lowlink, w.index)` is the correct way to update `v.lowlink` if w is on stack. Because `w` is on the stack already, `(v, w)` is a back-edge in the DFS tree and therefore `w` is not in the subtree of `v`. **Because `v.lowlink` takes into account nodes reachable only through the nodes in the subtree of `v` we must stop at `w` and use `w.index` instead of `w.lowlink.`**

Ref: https://en.wikipedia.org/wiki/Tarjan%27s_strongly_connected_components_algorithm#The_algorithm_in_pseudocode
