### ISSUE TITLE
Add algorithm to find Eulerian path on directed/undirected graph

### ISSUE THREAD

**Issue by williamfiset** [williamfiset/Algorithms#23]

**Comment by williamfiset** [comment]
Wrapped up directed version. Still need to verify undirected/directed versions can use the same code.

**Comment by garyyu** [comment]
Hi William,
What's the difficulty level for "Eulerian path"? And will you add eulerian circuit also?

**Comment by williamfiset** [comment]
I'd say medium, although I'm probably going to pick up the rest of the Euler path/circuit stuff because I want to make a video on the topic.

**Comment by garyyu** [comment]
Thanks for the quick feedback. 
I would like to know the exact algorithm difficulty measurement, it's O(V+E), O(VE), or something like that?
I ask this question because I'm looking for a puzzle which is hard to solve and easy to verify, I think eulerian circuit could be one.

**Comment by williamfiset** [comment]
Eulerian circuit can be solved in O(E) time and verified in O(E) so probably not what you're looking for. Try integer factorization for a problem that's hard to solve and easy to verify. Send me an email for further questions, I want keep this thread for dev
