### ISSUE TITLE
Gauss-Jordan

### ISSUE THREAD

**Issue by danthe1st** [williamfiset/Algorithms#230]
The Gauss-Jordan algorithm can be used in order to solve linear equations of any size using matrixes.

Note that the Gauss-Jordan algorithm is not the same as gaussean elimitation as gaussean elimitation is part of at.

I would like to add an implementation of the Gauss-Jordan algorithm.

**Comment by williamfiset** [comment]
I believe this already exists?

https://github.com/williamfiset/Algorithms/blob/master/src/main/java/com/williamfiset/algorithms/linearalgebra/GaussianElimination.java
