### ISSUE TITLE
Algorithms Playlist

### ISSUE THREAD

**Issue by ForgottenOneNyx** [williamfiset/Algorithms#232]
Hello William, 

Thanks for building the resources and the youtube videos. I have a question regarding your videos, I recently noticed that your algorithms playlist was no longer available (appears as doesn't exist). This is the webpage it used to be present in ([link](https://www.youtube.com/playlist?list=PLDV1Zeh2NRsAPGSY7R63cFtDfi6h9ij0f)). 

Is there any chance we can see the playlist again? It was a very helpful compilation!

Thanks. 

PS: I didn't know where else I could contact you regarding this, didn't mean to make it as an issue for your repo

**Comment by williamfiset** [comment]
Hey I removed the algorithms playlist because it was just a collection of videos already in other organized playlists like the ds playlist or the graph theory playlist. All the videos are still on youtube
