### ISSUE TITLE
Possible Improvement of graphtheory/DijkstrasShortestPathAdjacencyList.java

### ISSUE THREAD

**Issue by TianyiShi2001** [williamfiset/Algorithms#242]
https://github.com/williamfiset/Algorithms/blob/3bebbcd32053a7a5c2d2ae40490edcbfb8f3a424/src/main/java/com/williamfiset/algorithms/graphtheory/DijkstrasShortestPathAdjacencyList.java#L131-L159

Examining the above code reveals that `node.id` and `dist[node.id]` were not changed throughout the while block. Thus, the final `if` statement can be move to the beginning of the while block, which avoids one round of unnecessary computation. Is the `if` statement placed at the end intentionally?

**Comment by williamfiset** [comment]
Hummm I think you're mostly right that `dist[end]` isn't being updated in the last iteration. But I'm thinking maybe there's an edge case with negative self loops that would improve the cost that might be undetected if the last `if` statement is not at the end??

**Comment by TianyiShi2001** [comment]
Yes you are right! I haven't thought about self loops before. Thank you for your explanation!

**Comment by TianyiShi2001** [comment]
But the Dijkstras algorithm does not allow negative edge weights, as stated in your [video](https://www.youtube.com/watch?v=pSqmAO-m7Lk) (00:33). Otherwise, for example in the case of a self loop around node `i` with a negative edge weight, the distance of any two points that could pass through `i` can be made infinitely small by looping around node `i` infinite times.

**Comment by williamfiset** [comment]
True, in theory there shouldn't be any negative edges. However, that doesn't prevent anyone from actually setting up a graph as such (in which case you could detect the graph is badly setup). Maybe that's not a great excuse, but I would vouch to leave the code as is. Saving one iteration will not improve the time complexity anyways.
