### ISSUE TITLE
Typo in a presentation

### ISSUE THREAD

**Issue by skill-bit** [williamfiset/Algorithms#246]
Slides 84 and 85 of the [presentation](https://github.com/williamfiset/Algorithms/blob/master/slides/datastructures/priorityqueue/PriorityQueue.pptx) have a typo.

For a reference: 
A complete binary tree is a tree in which at every level, except possibly the last is completely filled and **and** all the nodes are as far left as possible.

**Comment by williamfiset** [comment]
Resolved. Thanks!
