### ISSUE TITLE
Question: Wouldn't proactive resize of the array be an overhead? 

### ISSUE THREAD

**Issue by skill-bit** [williamfiset/Algorithms#247]
Considering implementation supports caller-defined capacity through the constructor, wouldn't proactive resize of the array be an overhead for the implementation? 

For a reference:
https://github.com/williamfiset/Algorithms/blob/4bc566bb32232a2f9a9e3ad49d667f9d3f4f0fc7/src/main/java/com/williamfiset/algorithms/datastructures/dynamicarray/DynamicArray.java#L51

**Comment by williamfiset** [comment]
I think that's intended for a dynamic array. It needs to grow at some point. Are you saying there's an off by 1 error here?

**Comment by skill-bit** [comment]
I think it's better to use an example here. 

For a dynamic array with the capacity of 2: len = 0, cap = 2;
- arr.add(0): if (len + 1 >= capacity) is false, after item is added len = 1, cap = 2;
- arr.add(1): if (len + 1 >= capacity) is true -> **resize**, after item is added len = 2, cap = 4;
- arr.add(2): if (len + 1 >= capacity) is false, after item is added len = 3, cap = 4;
- arr.add(3): if (len + 1 >= capacity) is true, after item is added len = 4, cap = 8;

So the steps where we add 1 and 3 will result in the array growth but we still have room to add each item without performing growth. It is an edge case where I would rather delegate growth where it's actually needed.

Your thoughts?
