### ISSUE TITLE
Bug in FloydWarshallSolver for certain negative cycles

### ISSUE THREAD

**Issue by askenderski** [williamfiset/Algorithms#260]
The Floyd-Warshall algorithm, in its current implementation, does not work for every negative cycle.

`public static void main(String[] args) {
    // Construct graph.
    int n = 3;
    double[][] m = createGraph(n);

    // Add some edge values.
    m[1][2] = 1000;
    m[2][2] = -1;
    m[1][0] = 1;
    m[2][0] = 1;

    FloydWarshallSolver solver = new FloydWarshallSolver(m);
    double[][] dist = solver.getApspMatrix();

    for (int i = 0; i < n; i++)
      for (int j = 0; j < n; j++)
        System.out.printf("This shortest path from node %d to node %d is %.3f\n", i, j, dist[i][j]);

    System.out.println();

    // Reconstructs the shortest paths from all nodes to every other nodes.
    for (int i = 0; i < n; i++) {
      for (int j = 0; j < n; j++) {
        List<Integer> path = solver.reconstructShortestPath(i, j);
        String str;
        if (path == null) {
          str = "HAS AN ∞ NUMBER OF SOLUTIONS! (negative cycle case)";
        } else if (path.size() == 0) {
          str = String.format("DOES NOT EXIST (node %d doesn't reach node %d)", i, j);
        } else {
          str =
              String.join(
                  " -> ",
                  path.stream()
                      .map(Object::toString)
                      .collect(java.util.stream.Collectors.toList()));
          str = "is: [" + str + "]";
        }

        System.out.printf("The shortest path from node %d to node %d %s\n", i, j, str);
      }
    }
  }`

If this is put as the main code, the path from 1 to 0 is found to be 1 instead of the correct -Infinity (1 to 2 is 1000 and 2 is in a negative cycle, then 2 reaches 0).

The problem with the code is that the current code which checks for negative cycles needs to run twice instead of once, as is the case now. What I mean is, it should be replaced by this:

`for (int run = 0; run < 2; run++) {
        for (int k = 0; k < n; k++)
            for (int i = 0; i < n; i++)
                for (int j = 0; j < n; j++)
                    if (dp[i][k] + dp[k][j] < dp[i][j]) {
                        dp[i][j] = NEGATIVE_INFINITY;
                        next[i][j] = REACHES_NEGATIVE_CYCLE;
                    }
    }`

The reason for that is, sadly, somewhat complicated and I don't think I could explain it in just text. If someone is interested, I could try to show this using text and MS Paint (or we could talk, if that is not a problem) as I don't have any experience drawing graphs with code and don't think I could pull it off easily. Still, it should be noted that I'm not 100% sure it would work this way as I may have made a mistake, but I'm quite confident it would work.

However, this fix I provided would mean that the FloydWarshall algorithm runs thrice instead of just once as it would be if we were sure negative cycles didn't exist. This could be fixed if, instead of running it twice again to detect negative cycles, we just added all of the nodes which have a distance to themselves less than 0 to a stack. Nodes with a distance to themselves less than 0 are nodes which are part of a negative cycle and it is also true that all nodes which are a part of a negative cycle have a negative distance to themselves (the reason for this is, again, kind of complicated and would be hard to explain in just text). In this stack, for every node (which is every node part of a negative cycle) all reachable points should also be added to the stack (since they are affected by the nodes in the negative cycle) and every distance from a node in the stack to a reachable node should be changed to negative infinity. Since this would cause the stack to run forever (if nodes 0 and 1 are in a negative cycle, node 0 will add node 1 to the cycle again and node 1 will add node 0 to the cycle again and etc.), we could initialize a set with the nodes which have already been in the stack and only add to the stack nodes which aren't currently in a hash table.

**Comment by askenderski** [comment]
Sorry, but I noticed a note in the algorithm which says that usually the diagonal will be all 0-s. Does that mean that the algorithm isn't supposed to work with cases other than that? If that's so, please notify me to close the issue or close it yourself since I'm quite confident that the bug only manifests itself when there is a negative edge from a node to itself (and then only in specific cases).

**Comment by williamfiset** [comment]
Thanks for filing this issue. Your example clearly shows unexpected behaviour [I also expect the negative cycle to propagate]. I need to give this some more thought on how best to handle this. Your suggestion of running a third time is interesting and I need to do some of my own experimentation.

**Comment by askenderski** [comment]
Hi, I don't know if you have had the time to think about it, so maybe I could save you at least some time by giving you some ideas. A way which would also work and which I think would be more understandable, would be like this:

for (int k = 0; k < nodes.length; k++) {
  for (int i = 0; i < nodes.length; i++) {
    for (int j = 0; j < nodes.length; j++) {
      if (dist[i][k] !== Infinity && dist[k][k] < 0 && dist[k][j] !== Infinity) {
        dist[i][j] = Negative_Infinity;
      }
    }
  }
}

This makes use of the fact that all nodes in a negative cycle have a negative distance to themselves and that the distance between two nodes is negative infinity only if there is a path between them which goes through a negative cycle. Some easy optimizations can be made right away and the k-s with non-negative distance to themselves can be skipped and the i-s which can not reach the k-s (if (dist[i][k] == Infinity) continue;) can be skipped, too. Then, further optimizations can be made such as the outward cycle (k-cycle) being on the cycles instead of the nodes (if we have cycles [0,1,2] and [3,4,5], we don't need to go through 0, 1 and 2 since the same elements can reach 0, 1 and 2 and 0, 1 and 2 can reach the same elements, so we can just go through one of them. It would be relatively easy to do that since we can find if two nodes are part of the same negative cycle (or, rather, part of the same strongly connected component, but the 0, 1 and 2 logic also applies here) by just checking if they can both reach each other and both have a negative distance to themselves.).
Another way to solve this problem is to just stick a loop which goes through all the nodes and replaces the negative self-distances with NegativeInfinity. Everything else still works with the same logic as before and negative self-edges also propagate.
I haven't tested this in code, but it works in theory. It's kind of late right now, so if I have written something in a confusing manner, please tell me and I will get back to you as soon as I can :)

**Comment by soundaryasenthil02** [comment]
Hello devs,

Myself and 3 other students (@Visrutha, @AdithyaS99, @DDSSS07) are studying final year M.Sc Software Systems in PSG College Of Technology, India. We are interested in this repository of algorithms and would like to contribute to this project as we found this exciting to learn and collaborate. Could you let us know if there are possibilities for us to to contribute to the the existing and upcoming issues?

**Comment by Aariv** [comment]
Hi @soundaryasenthil02 

Could you please go through the repository or issues reported in the issues sections?

You could refer to this https://github.com/williamfiset/Algorithms/wiki for the contribution details. 

Thank you!

**Comment by soundaryasenthil02** [comment]
Hi @Aariv 
Thank you so much.

**Comment by williamfiset** [comment]
I believe this issue is actually resolved and just hasn't been closed.
