### ISSUE TITLE
Different results in Knapsack_01.java & KnapsackUnbounded.java for same input

### ISSUE THREAD

**Issue by elangoravi** [williamfiset/Algorithms#266]
Hi William,

I just identified that Knapsack_01.java and KnapsackUnbounded.java results in different max profit values for same input. I understand that the unbounded version is meant to be space efficient, with no other difference should be there between the two.

Input tried:
capacity = 10;
V = new int[] { 5, 20, 3 };
W = new int[] { 3, 6, 2 };

Results :
Knapsack_01 : 25 (Guess this should be the right one)
KnapsackUnbounded: 26

**Comment by williamfiset** [comment]
Knapsack_01 and Knapsack_01 should be two different implementation of the knapsack problem. In the 0/1 knapsack problem you can only select each element once, while in the unbounded knapsack problem you can select each element in infinite number of times (that is until you reach the capacity of the knapsack].

**Comment by williamfiset** [comment]
I think everything is WAI? Closing this issue unless something else is unclear

**Comment by elangoravi** [comment]
Thank you much for the explanation @williamfiset . Wasn't aware of this earlier..
