### ISSUE TITLE
Add algorithm to solve the Steiner tree problem.

### ISSUE THREAD

**Issue by williamfiset** [williamfiset/Algorithms#28]

**Comment by micahstairs** [comment]
I can do this one! But how do we handle dependencies on other algorithms? For example, this snippet depends on Floyd-Warshall.

**Comment by williamfiset** [comment]
I always include all the dependencies someone needs inside the one file for the particular algorithm I'm developing even if it's a lot of duplication. I feel like this is the best solution so that all algorithms work out if the box.

**Comment by micahstairs** [comment]
I guess the only issue is if we find a bug or something in the
Floyd-Warshall snippet and then have to change it in a lot of spots.

**Comment by williamfiset** [comment]
We could make the whole project use packages/imports but then each snippet no longer works on its own. A hacky way to avoid this would be to somehow automatically copy the dependencies into the file by running a code auto generation tool. That does seems like a lot of work ATM though so I would hold off.

**Comment by williamfiset** [comment]
@micahstairs this is done, correct?

**Comment by micahstairs** [comment]
Correct!
