### ISSUE TITLE
Dynamic Array's add function does not increment length

### ISSUE THREAD

**Issue by tempname0606** [williamfiset/Algorithms#290]
https://github.com/williamfiset/Algorithms/blob/028e979cbc094a784481d2f25b715614bfd93135/src/main/java/com/williamfiset/algorithms/datastructures/dynamicarray/DynamicArray.java#L58

I am going through the data structures playlist and I noticed that the length of the array is not incremented when adding a new element.

**Comment by Ayse-Sadioglu** [comment]
Can I have this issue?

**Comment by NeoLight1010** [comment]
I think the length is incremented in the last line using `len++`:

```java
arr[len++] = elem;
```

**Comment by tempname0606** [comment]
Yes, my bad

> I think the length is incremented in the last line using `len++`:
> 
> ```java
> arr[len++] = elem;
> ```

**Comment by KDPandit** [comment]
> Yes, my bad
> 
> > I think the length is incremented in the last line using `len++`:
> > ```java
> > arr[len++] = elem;
> > ```

Sorry, but how is the length being incremented here, only the new element is being added, **len** will still remain the same as before isn't it?

**Comment by KdB13** [comment]
@tempname0606 Please close this issue if your problem is solved. 🙂

**Comment by tempname0606** [comment]
Will do, thanks for reminding me.
