### ISSUE TITLE
Junit 5 ConcurrentModificationException update for BinarySearchTreeTest

### ISSUE THREAD

**Issue by mmaurier** [williamfiset/Algorithms#294]
Here's the code change for Junit 5 on BinarySearchTreeTest for ConcurrentModificationException:

@Test
public void concurrentModificationErrorRemovingPreOrder() throws ConcurrentModificationException {
		
	Assertions.assertThrows(ConcurrentModificationException.class, () -> {
			
		BinarySearchTree<Integer> bst = new BinarySearchTree<>();
			
		bst.add(1);
		bst.add(2);
		bst.add(3);
			
		Iterator<Integer> iter = bst.traverse(TreeTraversalOrder.PRE_ORDER);
			
		while (iter.hasNext()) {
			bst.remove(2);
			iter.next();
		}
	});
}

Same goes for InOrder, PostOrder, and LeveOrder test.

**Comment by williamfiset** [comment]
The current impl is using Junit 4 and is WAI. Please send a PR if you want to upgrade to Junit 5, altough that might breaks other tests along the way

https://github.com/williamfiset/Algorithms/blob/master/build.gradle#L35

**Comment by mmaurier** [comment]
Sounds good. I'll start a branch called 'Update Junit'. I'm studying for an interview with Google next month using your Algorithms repository and your youtube video also. Can you leave the branch open until I finish with the entire repository? This way we avoid breaking other test cases and you can test the branch at your own leisure.
