### ISSUE TITLE
Fix Bug at Binary Search 

### ISSUE THREAD

**Issue by mohanadtalat91** [williamfiset/Algorithms#297]
https://github.com/williamfiset/Algorithms/blob/19ae8ddf6d5af253cb61ea42d76bd8d073c46f35/src/main/java/com/williamfiset/algorithms/search/BinarySearch.java#L29

At **Line 29** : You'd prefer to use this equation `mid = lo + ((hi - lo) / 2.0) ` instead of at **Line 29** to face an overflow with big numbers

**Comment by williamfiset** [comment]
Feel free to submit a PR.

**Comment by mohanadtalat91** [comment]
I've submited a PR, I hope to add it 😊

**Comment by williamfiset** [comment]
Closing since this wasn't really a bug since the binary search was for floating point numbers
