### ISSUE TITLE
Dynamic Array - removeAt method

### ISSUE THREAD

**Issue by afshinpaydar-binary** [williamfiset/Algorithms#314]
This [line](https://github.com/williamfiset/Algorithms/blob/65dcc1bb0eea241d4c32c9c676540920d037bb76/src/main/java/com/williamfiset/algorithms/datastructures/dynamicarray/DynamicArray.java#L66) probably should be like this:
```
T[] new_arr = (T[]) new Object[capacity];
```
Because by creating array with `len -1` we end up with this:

```
arr = [1, 2, 3, nul, null, null]
arr.removeAt[1]
arr = [1,3]
```
but this is what we expect:
```
arr = [1, 2, 3, null, null, null]
arr.removeAt[1]
arr = [1,3, null, null, null, null]
```

**Comment by Madanaa** [comment]
@afshinpaydar-binary can we do this

**Comment by josephAttia** [comment]
@afshinpaydar-binary 

May you please provide a test case in which having null values present would be beneficial. 

I'll be happy to work on it if it would help users!

**Comment by afshinpaydar-binary** [comment]
@Madanaa doing what?
