### ISSUE TITLE
Command for Java formatter in Wiki Is Outdated

### ISSUE THREAD

**Issue by syoon2** [williamfiset/Algorithms#384]
With #383, this repo now uses Spotless instead of Sherter. This makes documentation about running the Java formatter outdated in the [wiki](../wiki) and the wiki should be updated/fixed.

The command for running Spotless should be updated to `./gradlew spotlessApply`.

**Comment by syoon2** [comment]
@williamfiset Just a kind ping - although I would like to contribute a fix myself, the permission settings on Wiki doesn't let me to 😢

**Comment by williamfiset** [comment]
Thanks for the ping, updated step 7 on formatting!
