### ISSUE TITLE
 Addition of FIFO (First-In-First-Out) Functionality

### ISSUE THREAD

**Issue by AnaBeatrizMassuh** [williamfiset/Algorithms#386]
Hello everyone! I've created this issue to propose the addition of FIFO (First-In-First-Out) functionality to the system. FIFO is a crucial feature that ensures the order of data processing, where the first item that enters the system is the first one to be processed. By implementing FIFO, we can enhance the efficiency and fairness of our system, particularly in scenarios where strict ordering is required. I believe this feature will greatly benefit our users and contribute to a more seamless user experience. Looking forward to discussing and collaborating on this idea with all of you! 😊

**Comment by williamfiset** [comment]
By FIFO, you mean a [Queue](https://en.wikipedia.org/wiki/Queue_(abstract_data_type)) data structure? There already exists 4 implementations in this repo:

https://github.com/williamfiset/Algorithms/tree/master/src/main/java/com/williamfiset/algorithms/datastructures/queue
