### ISSUE TITLE
Cut polygon additional points

### ISSUE THREAD

**Issue by williamfiset** [williamfiset/Algorithms#59]
The [cut polygon](https://github.com/williamfiset/Algorithms/blob/master/Geometry/ConvexPolygonCutWithLineSegment.java) snippet seems to provide additional points when a cut operation is performed which probably shouldn't be there. 

For example, when the following runs the additional point (2,2) appears out of nowhere.

```java
    Pt[] squarePolygon = {new Pt(0, 0), new Pt(0, 4), new Pt(4, 0), new Pt(4, 4)};
    Pt p1 = new Pt(-1, -1);
    Pt p2 = new Pt(5, 5);

    Pt[] poly1 = cut(squarePolygon, p1, p2);
    Pt[] poly2 = cut(squarePolygon, p2, p1);

    System.out.println("First polygon:");
    for (Pt pt : poly1) System.out.println(pt);
    // Prints:
    // First polygon:
    // (4.0,4.0)
    // (0.0,0.0)
    // (0.0,4.0)
    // (2.0,2.0) <-- Probably should not be here?
    
    System.out.println("\nSecond polygon:");
    for (Pt pt : poly2) System.out.println(pt);
    // Second polygon:
    // (4.0,4.0)
    // (0.0,0.0)
    // (2.0,2.0) <-- Probably should not be here?
    // (4.0,0.0)
```

@FinnLidbetter assigning you since made this snippet right? Perhaps you can offer some insight.

**Comment by FinnLidbetter** [comment]
I can take a look, although I think Micah put this one together.

**Comment by micahstairs** [comment]
Hmm those (2,2)s definitely shouldn't be there, I graphed it out.

Maybe this snippet only behaves badly when you cut directly through
vertices?
