### ISSUE TITLE
Why is there a loop in AngleBetweenVectors2D.java ?

### ISSUE THREAD

**Issue by atakanyenel** [williamfiset/Algorithms#66]
In the end of the main in Geometry `AngleBetweenVectors2D.java`, there is a loop that runs for 100000 times. `Math.random` defines the variable `v` once every iteration and calculations are done with vectors with same v value. The result of first calculation is always 180 degrees, and second is 0. Running it 100000 times will still give the same result for each iteration. 

Is the loop there just to show speed ? Am I missing something ?

**Comment by williamfiset** [comment]
Hi Atakan, the loop is just generating vectors and finding the angle between the vectors to show that the method 'angleBetweenVectors' actually works.

**Comment by williamfiset** [comment]
Got rid of the code because it might be confusing, thanks for pointing this out.
