### ISSUE TITLE
Suffix Array LCS broken?

### ISSUE THREAD

**Issue by williamfiset** [williamfiset/Algorithms#70]
Investigate the behavior of the LCS method under different k values to determine if it's working properly -- especially with long strings.

I haven't looked into the details yet, but assuming the initial approach is still correct and there's just a bug in the code (which is quite possible) it may be worth investigating to see if we can swap out the current SA implementation with the slower but more stable [implementation](https://github.com/williamfiset/data-structures/blob/master/com/williamfiset/datastructures/suffixarray/SuffixArraySlow.java). If that doesn't work, I can also swap out the sliding window minimum with a [min range query segment tree](https://github.com/williamfiset/data-structures/blob/master/com/williamfiset/datastructures/segmenttree/CompactSegmentTree.java) to see if I get a different result.

**Comment by williamfiset** [comment]
Added [Lcs.java](https://github.com/williamfiset/Algorithms/blob/master/com/williamfiset/algorithms/strings/Lcs.java) and it seems to be working ATM. I will replace LongestCommonSubstring.java when sufficient testing has been done.

**Comment by IsraaMa** [comment]
<img width="1273" alt="Screen Shot 2019-04-01 at 2 58 24 PM" src="https://user-images.githubusercontent.com/41713557/55359257-a7deda80-548e-11e9-8d12-c2472a121b17.png">
Here we can see the bug. The first part (left)  shows the dataset used to test the algorithm. The second part (middle) shows the output of LongestCommonSubstring.java, the expected (correct) results are shown on the third box (right).  

We can see that on k_value = 3,6 and 7 the output doesn't match the expected result. 

**Possible reasons of the bug:**
-*Sliding window*: When k = 3 the LongestCommonSubstring.java algorithm outputs ·"AAT" & "ATA". "ATA"  is the longest substring but only for users 2 and 3. On the other hand "AAT" has the same length, but again, K was set to 3 and such substrings are only present in 2 of the 3 accounts.

**Comment by williamfiset** [comment]
Should be working now! Please re-open if you find a breaking test case
