### ISSUE TITLE
Add Treap data structure implementation

### ISSUE THREAD

**Issue by williamfiset** [williamfiset/Algorithms#76]

**Comment by jzisheng** [comment]
Hey just started working on this, and would appreciate some advice

I've placed TreapTree class and test in `balancedtree/` category, as I believe this is the best fit(just wanted to confirm this)

For generating random priorities, should it matter what I set the priority bound to(using `random.random(N)`)? Maybe I should make it an attribute?

And finally [here is my current repo](https://github.com/jzisheng/Algorithms/blob/master/src/main/java/com/williamfiset/algorithms/datastructures/balancedtree/TreapTree.java) (I couldn't see a 'draft pull request') but just wanted to check in on expectations of public methods that should be included with balanced trees.  I've based mine off of the BST class implementation - do let me know if I am missing any

**Comment by williamfiset** [comment]
> I've placed TreapTree class and test in balancedtree/ category, as I believe this is the best fit(just wanted to confirm this)

Yes the balancedtree/ is where I would place the treap

> For generating random priorities, should it matter what I set the priority bound to(using random.random(N))? Maybe I should make the bound an attribute?

I've never implemented a treap, but my guess is the priority can just be a number between 0 and 1, so Math.random() is probably ok. My understanding is that each node maintains a priority p, and after each insertion/deletion you simply perform tree rotations (https://www.youtube.com/watch?v=q4fnJZr8ztY) on the callback where the priority of the parent node is greater than the child. This should keep the tree mostly balanced it seems.

> And finally here is my current repo (I couldn't see a 'draft pull request') but just wanted to check in on expectations of public methods that should be included with balanced trees. I've based mine off of the BST class implementation - do let me know if I am missing any

lgtm!
