### ISSUE TITLE
Add comment

### ISSUE THREAD

**Issue by skrzypecki** [williamfiset/Algorithms#99]
https://github.com/williamfiset/Algorithms/blob/dcf94d6cef0100a83acab2349a4ca9194d7056ba/com/williamfiset/algorithms/graphtheory/DepthFirstSearchAdjacencyListIterative.java#L59

It is not obvious at first why there are 5 nodes. Create a fully connected graph defines 3 nodes with edges and 1 node without edges. Node 4 is not defined explicitly.

**Comment by williamfiset** [comment]
This is intentional to verify the behavior of the algorithm. Feel free to submit a PR if you want to clarify things.
